// action types for API calls

export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const FETCH_SEARCH_RESULTS_REQUEST = 'FETCH_SEARCH_RESULTS_REQUEST';
export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS';

export const FETCH_ARTIST_REQUEST = 'FETCH_ARTIST_REQUEST';
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS';
export const SWITCH_CURRENT_ARTIST = 'SWITCH_CURRENT_ARTIST'; 

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_HIGHLIGHTS_REQUEST = 'FETCH_HIGHLIGHTS_REQUEST';
export const FETCH_HIGHLIGHTS_SUCCESS = 'FETCH_HIGHLIGHTS_SUCCESS';

export const FETCH_ORPHAN_ALBUM_REQUEST = 'FETCH_ORPHAN_ALBUM_REQUEST';
export const FETCH_ORPHAN_ALBUM_SUCCESS = 'FETCH_ORPHAN_ALBUM_SUCCESS';

export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';

export const FETCH_PLAYLIST_REQUEST = 'FETCH_PLAYLIST_REQUEST';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const UPDATE_PLAYLIST_IMAGE = 'UPDATE_PLAYLIST_IMAGE';
export const UPDATE_PLAYLIST_IMAGE_SUCCESS = 'UPDATE_PLAYLIST_IMAGE_SUCCESS'; 
export const UPDATE_PLAYLIST_NAME = 'UPDATE_PLAYLIST_NAME';
export const UPDATE_PLAYLIST_NAME_SUCCESS = 'UPDATE_PLAYLIST_NAME_SUCCESS';
export const DELETE_TRACK_FROM_PLAYLIST = 'DELETE_TRACK_FROM_PLAYLIST';
export const DELETE_TRACK_FROM_PLAYLIST_SUCCESS = 'DELETE_TRACK_FROM_PLAYLIST_SUCCESS';
export const ADD_TRACK_TO_PLAYLIST = 'ADD_TRACK_TO_PLAYLIST';
export const ADD_TRACK_TO_PLAYLIST_SUCCESS = 'ADD_TRACK_TO_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';


export const SWITCH_CURRENTLY_SELECTED_COLLECTION = 'SWITCH_CURRENTLY_SELECTED_COLLECTION';
export const UPDATE_CURRENTLY_SELECTED_COLLECTION = 'UPDATE_CURRENTLY_SELECTED_COLLECTION';
export const PLAY_PAUSE_FROM_PLAYER = 'PLAY_PAUSE_FROM_PLAYER';
export const SKIP_TO_NEXT_TRACK = 'SKIP_TO_NEXT_TRACK';
export const SKIP_TO_PREVIOUS_TRACK = 'SKIP_TO_PREVIOUS_TRACK';
export const SHUFFLE_CURRENT_COLLECTION = 'SHUFFLE_CURRENT_COLLECTION';
export const UNSHUFFLE_CURRENT_COLLECTION = 'UNSHUFFLE_CURRENT_COLLECTION';
export const SCRUB_TRACK = 'SCRUB_TRACK';
export const TOGGLE_REPEAT = 'TOGGLE_REPEAT';

// other action types

export const STORE_TOKEN = 'STORE_TOKEN';
export const SET_MARKET = 'SET_MARKET';

export const ADD_TRACK_MODAL_OPEN = 'ADD_TRACK_MODAL_OPEN';
export const ADD_TRACK_MODAL_CLOSE = 'ADD_TRACK_MODAL_CLOSE';

